---
title: "Microeconomia 1 (Lista 1)"
author: "Frederico Fonseca Ribeiro"
format: 
    pdf: 
     include-in-header:  
        - text: |
            \usepackage{physics}
            \newcommand{\Lagr}{\mathcal{L}}
crossref:
  eq-prefix: Equação
---

# Questão 1

# Questão 2
## a) 
$$
UMg_1 = \frac{\partial u}{\partial x_1} = x_2
$$
De forma semelhante, , encontramos a utilidade maginal de $x_2$ e temos que a $TMgS = \frac{UMg_1}{UMg_2} = \frac{x_2}{x_1}$

## b)

De forma semelhante, temos que:
$$
TMgS = \frac{2 x_1 x^2}{2 x_1^2 x_2}
$$

## c) 
$$
TMgS = \frac{1/x_1}{1/x_2}
$$

# Questão 3

## a)
Demonstrando homogeneidade de grau zero:


\begin{align}
x_1(p,w) &= x(kp, kw) \\
\left( \frac{2w}{2p_1 + p_2} \right) &= \left( \frac{k2w}{k2p_1 + kp_2} \right) \\
&= \left( \frac{k(ww)}{k(2p_1 + p_2)} \right) \\
&= \left( \frac{2w}{2p_1 + p_2} \right)
\end{align}

Demonstrando Lei de Walras:

\begin{align}
px &= w \\
p_1x_1 + p_2x_2 &= w \\
p_1 \left(\frac{2w}{2p_1 + p_2} \right) + p_2 \left(\frac{w}{2p_1 + p_2} \right) &= w \\
w \left(\frac{2p_1 + p_2}{2p_1 + p_2}\right) &= w \\
w &= w
\end{align}

# b) 

Demonstrando grau de homogeneidade 0 para $x_1$, sendo os outros casos análogos:

\begin{align}
x_1(p,w) &= x(kp, kw) \\
\left(\frac{p_2w}{(p_1+p_2+p_3)p_1}\right) &= \left(\frac{kp_2kw}{(kp_1+kp_2+kp_3)kp_1}\right) \\
&= \left(\frac{k^2p_2w}{k^2(p_1+p_2+p_3)p_1}\right) \\
&= \left(\frac{p_2w}{(p_1+p_2+p_3)p_1}\right)
\end{align}

Demonstrando Lei de Walras

\begin{align}
w &= px \\
 &=  p_1 \left(\frac{p_2w}{(p_1+p_2+p_3)p_1}\right) + p_2\left(\frac{p_3w}{(p_1+p_2+p_3)p_2}\right) +
p_3 \left(\frac{\beta p_1w}{(p_1+p_2+p_3)p_3}\right) \\
&= \left(\frac{p_2w + p_3w + \beta p_1w}{p_1 + p_2 + p_3}\right) \\
&= \frac{w(\beta p_1 + p_2 +  p_3)}{p_1 + p_2 +  p_3} \\
&= w \textnormal{, se $\beta$ = 1}
\end{align}


# Questão 4

Provando homogeneidade de grau zero:
\begin{align}
x_1(kp, kw) &= \frac{kp_2}{kp_3} = \frac{p_2}{p_3} = x_1(p,w) \\
x_2(kp, kw) &=- \frac{kp_1}{kp_3} = - \frac{p_1}{p_3} = x_2(p,w) \\
x_3(kp, kw) &= \frac{kw}{kp_3} = \frac{w}{p_3} = x_3(p,w)
\end{align}
Provando Lei de Walras:

$$
p_1 \left(\frac{p_2}{p_3}\right) + p_2 \left(-\frac{p_1}{p_3}\right) + p_3 \left(\frac{w}{p3}\right) = w 
$$
Os dois primeiros termos se anulam e os $p_3$ também se anulam no terceiro termo, sendo assim:

$$
w = w
$$

# Questão 5
## Cobb-Douglas

### a)
Para mostrar que que é homotética, deve-se provar a homogeneidade de grau 1:

\begin{align}
tu(x_1, x_2) &= u(tx_1, tx_2) \\
&= u(K(tx_1)^\alpha (tx_2)^{1-\alpha}) \\
&= Kt^\alpha x_1^\alpha t^{1-\alpha}x_2^{1-\alpha} \\
&= tKx_1^\alpha x_2^{1-\alpha}
\end{align}

### b)

Para encontrar a demanda Walrasiana, ou seja, em função de $p$ e de $w$, devemos
maximizar a função sujeita à restrição orçamentária, sendo assim temos o seguinte lagrangeano:

$$
\mathcal{L} = Kx_1^\alpha x_2^{1-\alpha} + \lambda(w - p_1x_1 - p_2x_2)
$$ {#eq-lagrcd}

Sendo assim, temos as seguintes condições de primeira ordem:

$$
\pdv{\Lagr}{x_1} = \alpha Kx_1^{\alpha-1}x_2^{1-\alpha} - \lambda p_1 = 0
$$ {#eq-dvx1cb}

$$
\pdv{\Lagr}{x_2} = (1-\alpha)Kx_1^\alpha x_2^{-\alpha} - \lambda p_2 = 0
$$ {#eq-dvx2cb}

$$
\pdv{\Lagr}{\lambda} = w - p_1x_1 - p_2x_2 = 0
$$ {#eq-dvwcb}

Isolando $\lambda$ e substituindo dentro de @eq-dvx1cb, temos que:

$$
K\alpha x_1^{\alpha -1}x_2^{1-\alpha} = p_1 \left(\frac{(1-\alpha)Kx_1^\alpha x_2^{-\alpha}}{p_2}  \right)
$$
Podemos eliminar $K$ dos dois lados. Além disso, para isolar $x_2$, dividimos 
ambos os lados por $x_1^{\alpha -1}$ e multiplicamos por $x_2^{\alpha}$, restando:

$$
x_2 = \frac{p_1}{p_2}\frac{(1-\alpha)}{\alpha}x_1
$$ {#eq-dmx2}

Substituindo na @eq-dvwcb, temos que:

$$
w - p_1x_1 - p_2\left( \frac{p_1}{p_2}\frac{(1-\alpha)}{\alpha}x_1\right) 
$$

$$
p_1x_1 + \left( p_1\frac{(1-\alpha)}{\alpha}x_1\right)=   w
$$
$$
p_1x_1 \left(1 + \frac{(1-\alpha)}{\alpha}  \right) = w
$$
$$
p_1x_1 \frac{1}{\alpha}   = w
$$
E chegamos à demanda Walrasiana de $x_1$:

$$
x_1^*(p,w) = \frac{w \alpha}{p_1}
$$ {#eq-dmwx1}

Similarmente, encontramos $x_2^*(p,w)$:

$$
x_2^*(p,w) = \frac{w (1-\alpha)}{p_2}
$$ {#eq-dmwx2}

### c)

Para encontrarmos a função de utilidade indireta, precisamos substituir a demanda
Walrasiana dentro da função utilidade:

$$
v(p, w) =   Kw\left(\frac{w\alpha}{p_1}  \right)^\alpha \left(\frac{w(1-\alpha)}{p_2}  \right)^{1-\alpha}
$$



### d)

### e)
Para acharmos a demanda Hicksiana, devemos minimizar o gasto em função da utilidade, 
sendo assim, temos:

$$
\mathcal{L} = p_1x_1 + p_2x_2 + \lambda(u - Kx_1^\alpha x_2^{-\alpha})
$$
Condições de primeira ordem:

$$
\pdv{\Lagr}{x_1} = p_1 + \lambda K\alpha x_1^{\alpha-1}x_2^{1-\alpha} = 0
$$ {#eq-dvhx1cb}
$$
\pdv{\Lagr}{x_2} = p_2 + \lambda K(1-\alpha) x_1^{\alpha}x_2^{-\alpha} = 0
$$ {#eq-dvhx2cb}
$$
\pdv{\Lagr}{\lambda} = u - Kx_1^\alpha x_2^{-\alpha}) = 0
$$ {#eq-dvhlcb}

Isolando $\lambda$ na @eq-dvhx2cb e substituindo na @eq-dvhx1cb, temos:

$$
p_1 - \frac{p_2hK\alpha x_1^{\alpha-1}x_2^{1-\alpha}}{K(1-\alpha) x_1^{\alpha}x_2^{-\alpha}} =
p_1 - \frac{p_2\alpha x_1^{-1}x_2^1}{(1-\alpha)} = 0
$$
Isolando $x_2$:

$$
x_2 = \frac{p_1}{p_2}\frac{(1-\alpha)}{\alpha}x_1
$$ {#eq-dmx2hcb}

Substituindo a @eq-dmx2hcb na @eq-dvhlcb:

$$
u - Kx_1^\alpha\left(\frac{p_1}{p_2}\frac{1-\alpha}{\alpha}x_1\right)^{1-\alpha} = 0
$$
Isolando $x_1$:

$$
x_1 = \frac{u}{K}\left(\frac{p_2}{p_1}\frac{\alpha}{1-\alpha}\right)^{1-\alpha} = h_1^*(p,u)
$$ {#eq-dhh1cb}
Semelhantemente, encontra-se $h_2^* =  \frac{u}{K}\left(\frac{p_1}{p_2}\frac{1-\alpha}{\alpha}\right)^{\alpha}$

### f)

Para achar a função dispêndio, basta substituir a demanda Hicksiana dentro:

\begin{align}
e(p, u) &= p_1 \frac{u}{K} \left[ \frac{\alpha}{1 - \alpha}   \frac{p_2}{p_1} \right]^{1 - \alpha} 
+ p_2   \frac{u}{K} \left[ \frac{1 - \alpha}{\alpha}   \frac{p_1}{p_2} \right]^{\alpha} \\
&= \frac{u}{K} p_1^{\alpha} p_2^{1 - \alpha} 
\left[ \frac{\alpha^{1 - \alpha}}{(1 - \alpha)^{1 - \alpha}} + \frac{(1 - \alpha)^{\alpha}}{\alpha^{\alpha}} \right] \\
&= \frac{u}{K} p_1^{\alpha} p_2^{1 - \alpha} 
\left[ \alpha^{-\alpha} (1 - \alpha)^{-(1 - \alpha)} \right]
\end{align}


### g)

Aplicando o Lema de Shephard, basta derivar a função dispêndio em relação ao preço:


$$
\frac{\partial e(p,u)}{\partial p_1} = \frac{u}{K}\left(\frac{p_2}{p_1}\frac{\alpha}{1-\alpha}\right)^{1-\alpha} = h_1^*(p,u)
$$
Nota: o expoente $\alpha$ que desce multiplicando ajuda na simplificação ao evidenciar o 
expoente dos parênteses dos termos à direita.

## h)

Para encontrar os efeitos Renda, Substituição e Total, devemos usar a Equação de 
Slutsky.

## CES



# Questão 6

Podemos definir a renda real como $R = w - p_0x$. A partir da @eq-dmwx1, temos que:

$$
x-x_0 = \frac{R\alpha}{p_x} =\frac{( w - px_0)\alpha}{p_x}
$$
Ou seja, como se gasta primeiro com $x_0$, há uma redução da reta orçamentária real.

# Questão 7

## a)
Para resolver a questão, devemos utilizar a Identidade de Roy, sendo assim:

$$
x_1^*(p,w) = -\frac{-\alpha/p_1}{(\alpha + \beta)/w} = \frac{\alpha}{(\alpha+\beta)}\frac{w}{p_1}
$$
Similarmente, para $x_2$: 

$$
x_2^*(p,w) =  \frac{\beta}{(\alpha+\beta)}\frac{w}{p_2}
$$

## b)

Para encontrar a função dispêndio, basta isolar $w$:

$$
\ln w = \frac{\alpha\ln p_1 + \beta\ln p_2 -K+u}{(\alpha + \beta)}
$$
Usando propriedades logarítimicas e depois usando função exponencial, tem-se que:

$$
e(p, u) = e^{\frac{u - K}{\alpha + \beta}} p_1^{\frac{\alpha}{\alpha + \beta}} p_2^{\frac{\beta}{\alpha + \beta}}
$$
Para chegar à Demanda Hicksiana, aplica-se o Lema de Shephard, que é 
a derivação da função dispêndio pelo preço:

$$
h_1(p, u) = \frac{\alpha}{\alpha + \beta} \, e^{\frac{u - K}{\alpha + \beta}} \left( \frac{p_2}{p_1} \right)^{\frac{\beta}{\alpha + \beta}}
$$
Semelhantemente, para o outro bem:

$$
h_2(p, u) = \frac{\beta}{\alpha + \beta} \, e^{\frac{u - K}{\alpha + \beta}} \left( \frac{p_1}{p_2} \right)^{\frac{\alpha}{\alpha + \beta}}
$$
# Questão 8

Para esta questão, considere $\alpha = 1/2$

Logo, a fim de maximizar a utilidade dada uma restrição orçamentária, temos as seguintes CPOs:

$$
\alpha x_1^{\alpha-1} + \lambda p_1 = 0
$$
$$
(1-\alpha) x_2^{-\alpha} + \lambda p_2 = 0
$$
$$
w - p_1x_1 - p_2x_2 = 0
$$
Igualando as equações, temos que:

$$
\frac{(1-\alpha) x_2^{-\alpha}}{p_2} = \frac{\alpha x_1^{\alpha-1}}{p_1}
$$
Isolando:

$$
x_2^\alpha = \frac{p_1}{p_2}\frac{\alpha}{(1-\alpha)}x_1^{\alpha-1}
$$
$$
x_2 = \left(\frac{p_1}{p_2}\frac{\alpha}{(1-\alpha)x_1^{1-\alpha}}\right)^\frac{1}{\alpha}
$$
Reduzindo ao substituir $\alpha$:

$$
x_2 = \left(\frac{p_1}{p_2}\right)^2x_1
$$
Substituindo na restrição orçamentária:

$$
w = p_1x_1 + p_2\left(\frac{p_1}{p_2}\right)^2x_1
$$
$$
x_1^* = \frac{w}{p_1+\frac{p_1^2}{p_2}}
$$
$$
x_1^* = \frac{p_2w}{p_1p_2+p_1^2}
$$
Similarmente:
$$
x_2^* = \frac{p_1w}{p_1p_2+p_2^2}
$$
# Questão 9

# Questão 10

# Questão 11

# Questão 12 

# Questão 13

# Questão 14

# Questão 15



